turn_on:
  name: Turn On (with retry)
  description: Turn on a device with automatic retry logic via script.ensure_device_changes
  fields:
    entity_id:
      name: Entity
      description: The entity or entities to turn on
      required: true
      selector:
        entity:
          multiple: true
    brightness_pct:
      name: Brightness (%)
      description: Brightness percentage (0-100). Takes precedence over brightness.
      example: 75
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    brightness:
      name: Brightness (0-255)
      description: Brightness value (0-255). Used if brightness_pct is not provided.
      example: 192
      selector:
        number:
          min: 0
          max: 255
    color_rgb:
      name: RGB Color
      description: RGB color as a list of three integers [R, G, B]
      example: "[255, 100, 100]"
      selector:
        object:
    color_name:
      name: Color Name
      description: Named color (e.g., red, blue, homeassistant). Automatically converted to RGB.
      example: "red"
      selector:
        text:
    kelvin:
      name: Color Temperature (Kelvin)
      description: Color temperature in Kelvin (1000-12000)
      example: 3000
      selector:
        number:
          min: 1000
          max: 12000
          unit_of_measurement: "K"
    effect:
      name: Light Effect
      description: Light effect name (e.g., colorloop, random)
      example: "colorloop"
      selector:
        text:

turn_off:
  name: Turn Off (with retry)
  description: Turn off a device with automatic retry logic via script.ensure_device_changes
  fields:
    entity_id:
      name: Entity
      description: The entity or entities to turn off
      required: true
      selector:
        entity:
          multiple: true

toggle:
  name: Toggle (with retry)
  description: Toggle a device's state with automatic retry logic via script.ensure_device_changes
  fields:
    entity_id:
      name: Entity
      description: The entity or entities to toggle
      required: true
      selector:
        entity:
          multiple: true
